[package]
name = "crudo"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "Take slices from raw blocks"
repository = "https://github.com/SillyFreak/typst-packages/tree/main/crudo"
categories = ["text", "scripting", "utility"]
disciplines = []
keywords = []
# compiler = ""
exclude = [
  # docs and gallery are not needed in the final package
  "docs",
  "gallery",
]
